### PR TITLE
Fix Code Smells and other Sonaqube issues

### PR DESCRIPTION
**Pull request by Benjamin-Dippold**
Adressed some of the Build up technical debt and security issue, to ensure that the main branch always passes the quality gates.

### CODE REVIEW

**Review by Ne0Strix — DISMISSED** [review]
lgtm

**Review by Kranosos — DISMISSED** [review]
Looks good, nice work.

**Review by Ne0Strix — APPROVED** [review]
lebtm

**Review by Kranosos — APPROVED** [review]
Looking good

**Pull request merged**
