### PR TITLE
Feature/10 music and soundeffects

### PR DESCRIPTION
**Pull request by Kranosos**
This issue was not originally planned for this sprint, and it does not contain any sound effects beyond the background music. But I feel like there just would be something that is missing, if there is no music at all in our game, so i added it. 

Royalty for the used music:
Royalty Free Celtic Fantasy Music - "The Lone Wolf"
By Royalty Free Music - Alexander Nakarada
YouTube-Link: https://youtu.be/RN1THCKeaNsa

### CODE REVIEW

**Comment by Kranosos** [comment]
I sincerely hope, that the coverage is not a point of concern, although there are still 2.8% missing.

**Review by Ne0Strix — COMMENTED** [review]
a few subtle changes, but other than that nice 😎

**Review by Ne0Strix — APPROVED** [review]
Nice, finally some improvements to the UX, including tests 🤩 
LGTM 👍🏽

**Review by Benjamin-Dippold — APPROVED** [review]
LGTM

**Pull request merged**
