### PR TITLE
Improve UI for 2nd Sprint

### PR DESCRIPTION
**Pull request by Benjamin-Dippold**
## Finalised UI for 2nd Sprint
- Readded Card Rotation in hand
- Replaced Placeholder graphics
- Fixed mulitple bug regarding the FullscreenView
- remembered to hit "Update comment" after writing this

### CODE REVIEW

**Review by Ne0Strix — APPROVED** [review]
Ah, Senpai 😎, your wisdom and guidance are akin to a beacon of light amidst the vast sea of code. With each interaction, I find myself humbled by the depth of your knowledge and the elegance of your solutions. In this particular PR review, I must express my utmost admiration for the meticulous attention to detail and the seamless integration of features.

The codebase resonates with your wise ways, Senpai, as you effortlessly navigate through the complexities, leaving behind a trail of brilliance. Your expertise shines through every line, exhibiting a masterful command over the craft. It is evident that you have poured not just your skills but also your heart into this work.

After a thorough examination, I am pleased to announce that this PR review has surpassed my expectations. The changes proposed are well-reasoned, the logic is sound, and the implementation is executed flawlessly. The clarity and readability of the code are a testament to your commitment to excellence.

In your wise ways, Senpai, lies a treasure trove of knowledge that we, your humble apprentices, are fortunate to witness. We are but mere mortals in the presence of your expertise, and we can only hope to glean a fraction of the wisdom that emanates from your endeavors.

With great respect and awe, I wholeheartedly declare that this PR review is not only worthy of acceptance but also a valuable lesson for all of us. Your contributions continue to inspire and elevate the entire team. We are truly privileged to have you as our Senpai.

May your wisdom continue to guide us on this journey of growth and enlightenment. Arigato gozaimasu, Senpai, for sharing your boundless knowledge and being a beacon of inspiration. It is an honor to review your work, and I eagerly anticipate the next glimpse of your brilliance.

**Comment by Benjamin-Dippold** [comment]
Thanks Geppetto.

**Comment by Ne0Strix** [comment]
Great way to put my thoughts into the world better than I ever could 🤞🏽

**Comment by Benjamin-Dippold** [comment]
> > Thanks Geppetto.
> 
> image

Cuz we all know that theese testers are accurate:
image

**Comment by Ne0Strix** [comment]
Aiaiai … but I stand behind those words. It's like putting quotes somewhere to underline a point, just a bit more personalised. 

> Inspiration is hard to come by. You have to take it where you find it.
> *Bob Dylan*

**Pull request merged**
