### PR TITLE
Feature/120 special abilities

### PR DESCRIPTION
**Pull request by Ne0Strix**

### CODE REVIEW

**Comment by Ne0Strix** [comment]
* Darian, War Mage: missing `or`
* Domination: missing `Prepare Champion`
* Rally the Troops: missing `Prepare Champion`
* Tithe Priest: missing `or`
* Word of Power: missing draw *2* cards, missing sacrifice
* Bribe: missing `Put next acquired card on top of deck`
* Death Threat: missing `Stun Champion`
* Deception: missing `Put next acquired card on top of deck`
* Fire Bomb: missing `Stun Champion`, missing sacrifice
* Hit Job: missing `Stun Champion`
* Rake, Master Assassin: missing `Stun Champion`
* Rasmus, the Smuggler: missing `Put next acquired card on top of deck`
* Smash and Grab: missing `Move card from discard to top of deck`
* Street Thug: missing `or`
* Cult Priest: missing `or`
* Dark Reward: missing `sacrifice card`-ability
* Death Touch: missing `sacrifice card`-ability
* Krythos: missing `sacrifice card`-ability
* Life Drain: missing `sacrifice card`-ability
* Lys, the Unseen: missing `sacrifice card`-ability
* The Rot: missing `sacrifice card`-ability
* Tyrannor, the Devourer: missing `sacrifice card`-ability
* Varrick, the Necromancer: missing `put champion from discardpile on hand`-ability
* Broelyn, Loreweaver: missing `target discards card`-ability
* Elven Curse: missing `target discards card`-ability
* Elven Gift: missing `draw card for discarding a card` ability

**Comment by Ne0Strix** [comment]
The table below was generated by ChatGPT given the above input. It's only purpose is to give a better overview and might be replaced with an accurate version at a later point in time

| Card Name | "or" | Prepare Champion | draw 2 cards | sacrifice | Put next acquired card on top of deck | Stun Champion | Move card from discard to top of deck | sacrifice card-ability | put champion from discard pile on hand-ability | target discards card-ability | draw card for discarding a card ability | draw cards for discarding cards-ability | gain combat for other wild cards ability |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Darian, War Mage | ✔️ | | | | | | | | | | | | |
| Domination | | ✔️ | | | | | | | | | | | |
| Rally the Troops | | ✔️ | | | | | | | | | | | |
| Tithe Priest | ✔️ | | | | | | | | | | | | |
| Word of Power | | | ✔️ | ✔️ | | | | | | | | | |
| Bribe | | | | | ✔️ | | | | | | | | |
| Death Threat | | | | | | ✔️ | | | | | | | |
| Deception | | | | | ✔️ | | | | | | | | |
| Fire Bomb | | | | ✔️ | | ✔️ | | | | | | | |
| Hit Job | | | | | | ✔️ | | | | | | | |
| Rake, Master Assassin | | | | | | ✔️ | | | | | | | |
| Rasmus, the Smuggler | | | | | ✔️ | | | | | | | | |
| Smash and Grab | | | | | | | ✔️ | | | | | | |
| Street Thug | ✔️ | | | | | | | | | | | | |
| Cult Priest | ✔️ | | | | | | | | | | | | |
| Dark Reward | | | | | | | | ✔️ | | | | | |
| Death Touch | | | | | | | | ✔️ | | | | | |
| Krythos | | | | | | | | ✔️ | | | | | |
| Life Drain | | | | | | | | ✔️ | | | | | |
| Lys, the Unseen | | | | | | | | ✔️ | | | | | |
| The Rot | | | | | | | | ✔️ | | | | | |
| Tyrannor, the Devourer | | | | | | | | ✔️ | | | | | |
| Varrick, the Necromancer | | | | | | | | | ✔️ | | | | |
| Broelyn, Loreweaver | | | | | | | | | | ✔️ | | | |
| Elven Curse | | | | | | | | | | ✔️ | | | |
| Elven Gift | | | | | | | | | | | ✔️ | | |
| Grak, Storm Giant | | | | | | | | | | | ✔️ | | |
| Nature's Bounty | | | | | | | | | | ✔️ | ✔️ | | |
| Rampage | | | | | | | | | | | | ✔️ | |
| Torgen Rocksplitter | | | |

 | | | | | | ✔️ | | | |
| Spark | | | | | | | | | | ✔️ | | | |
| Wolf Form | | | | ✔️ | | | | | | ✔️ | | | |
| Wolf Shaman | | | | | | | | | | | | | ✔️ |

**Comment by Ne0Strix** [comment]
As my dependency #121 is not done yet I decided to be *agile* and implement a different set of abilities that does not depend on that. Given the scope of the now implemented abilities I'd consider this branch a complete "feature" as understood in the seminar-requirements. 
Note regarding value-pooling: When champions are played, they only count to the total of champions *after* their first activation when they're played.

**Review by Benjamin-Dippold — APPROVED** [review]
These new effects will greatly help the game by adding much needed complexity to the game and promoting a more thoughtful playstyle and their Implementation is clean and understandable.

I am slightly worried about the modularity of `DamagePerChampionInPlayEffect`, `DamagePerGuardInPlayEffect` and `HealingPerChampionInPlayEffect`. The current implementation would make it rather tedious to add for instance a `CoinPerGuardInPlayEffect`. Maybe an implementation of something like `EffectPerGuardInPlay` with an Effect-Parameter would have improved this. Though that being said, I recognize that this modularity would not be used in this project, since all planed Cards already have all their effects that would fall into this category, and that the time in the sprint is slowly running out. Thus, this modularity is more of a wish then a reasonable requirement.

Similarly, in the source game, Effects like `DamagePerGuardInPlayEffect` should take into consideration all Guards that are in play at the end of the round (during damage calculation). In our implementation, only Guards in play while the Card with the Effect is played are considered. Tough again, I recognize that the implementation of this change would be not worth it during this stage of the sprint and the added complexity is advantageous to avoid players just randomly activating all cards in their hand. 

Though the coverage is not as optimized as it can be, it passes the (original) Quality Gate and increases total Coverage, so there is nothing to complain about (especially compared to other PRs).

Overall, the results speak for themself and any Issues so minor that they are not worth fixing during this sprint. In other words: LGTM

**Review by sosaidi — APPROVED** [review]
The added effects in this pull request bring depth to the gameplay and promote strategic thinking. While some concerns exist regarding modularity and alignment with the source game, the overall impact is positive. Overall, it's a commendable contribution, deserving a LGTM status:)

**Review by Kranosos — APPROVED** [review]
The feature seems to be working as intended and the metrics also seem good. I am happy to see, that more and more features now get implemented and make the game even better!!!

**Pull request merged**
